version: 2

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
